import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">SolnamesDomaindetails</Link>
        </li>
        <li>
          <Link to="/domainclickoverview">DomainClickOverView</Link>
        </li>
        <li>
          <Link to="/viewdetails">ViewDetails</Link>
        </li>
        <li>
          <Link to="/viewdetailsone">ViewDetailsOne</Link>
        </li>
        <li>
          <Link to="/wallets">Wallets</Link>
        </li>
        <li>
          <Link to="/walletsone">WalletsOne</Link>
        </li>
        <li>
          <Link to="/domainexplorefullopen">DOmainexplorefullopen</Link>
        </li>
        <li>
          <Link to="/domainlistfilterclose">DomainListFilterClose</Link>
        </li>
        <li>
          <Link to="/domainlistactivityclose">DomainListActivityClose</Link>
        </li>
        <li>
          <Link to="/domainlistfilterandactivityclose">
            DomainListFilterandActivityClose
          </Link>
        </li>
        <li>
          <Link to="/homepage">Homepage</Link>
        </li>
        <li>
          <Link to="/editprofile">EditProfile</Link>
        </li>
        <li>
          <Link to="/solnamesprofile">SolnamesProfile</Link>
        </li>
        <li>
          <Link to="/solnamessubdomains">SolnamesSubdomains</Link>
        </li>
        <li>
          <Link to="/solnamesdomaindetailsone">SolnamesDomaindetailsOne</Link>
        </li>
        <li>
          <Link to="/solnamesviewdomain">SolnamesViewDomain</Link>
        </li>
        <li>
          <Link to="/buymodal">BuyModal</Link>
        </li>
        <li>
          <Link to="/solnameschoosetokentoconnectwith">
            SolnamesChoosetokentoconnectwith
          </Link>
        </li>
        <li>
          <Link to="/solnamescheckout">SolnamesCheckout</Link>
        </li>
        <li>
          <Link to="/solnamestrasnferdomainnameone">
            SolnamesTrasnferdomainnameOne
          </Link>
        </li>
        <li>
          <Link to="/solnameschoosesubdomainwalletwith">
            SolnamesChooseSubdomainWalletwith
          </Link>
        </li>
        <li>
          <Link to="/solnamessubdomaincheckout">SolnamesSubdomainCheckout</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
